#!/bin/zsh

ensure-file() {
  if [[ ! -f $1 ]]; then
    touch $1
  fi
}

add-zshrc() {
  echo "Sourcing zshrc in ~/.zshrc ..."
  ensure-file ~/.zshrc
  echo "source ~/.dotfiles/zshrc" >> ~/.zshrc
  echo "" >> ~/.zshrc
}

add-gitconfig() {
  echo "Including gitconfig in ~/.gitconfig ..."
  ensure-file ~/.gitconfig
  echo "[include]" >> ~/.gitconfig
  echo "  path = ~/.dotfiles/gitconfig" >> ~/.gitconfig
  echo "[user]" >> ~/.gitconfig
  echo -n "What is your git name? "
  read yourname
  echo "  name = $yourname" >> ~/.gitconfig
  echo -n "What is your git email address? "
  read youremail
  echo "  email = $youremail" >> ~/.gitconfig
  echo "" >> ~/.gitconfig
}

add-vimrc() {
  echo "Symlinking vim directory to ~/.vim ..."
  if [[ ! -d ~/.vim ]]; then
    ln -s ~/.dotfiles/vim ~/.vim
  else
    echo "/!\\  ~/.vim already exists"
  fi
}

add-all() {
  add-zshrc
  add-gitconfig
  add-vimrc
}

install-brew() {
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}

$1

